name: Docker Image CI

on:
  push:
    branches: [ "product" ]
  pull_request:
    branches: [ "product" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: make  IMAGE=caydic_sheet:$(date +%s) build
    - name : Erase container
      run : make erase 
    - name : Create container
      run : make IMAGE=caydic_sheet:$(date +%s) run
   
