name: Docker Image CI

on:
  push:
    branches: [ "product" ]
  pull_request:
    branches: [ "product" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: sudo docker build . --file Dockerfile --tag caydic_sheet:$(date +%s)
    - name : Erase container
      run : make erase 
    - name : Create container
      run : make IMAGE=caydic_sheet:$(date +%s) run
   
